port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - 负载均衡
      - 失败切换
      - DIRECT
  - name: 自动选择
    type: url-test
    url: 'https://github.com/explore'
    interval: 60
    lazy: true
    tolerance: 500
    proxies:
  - name: 负载均衡
    type: load-balance
    strategy: consistent-hashing
    url: https://github.com/explore
    interval: 300
    tolerance: 200
    proxies:
  - name: 失败切换
    type: fallback
    url: https://github.com/explore
    interval: 300
    tolerance: 200
    proxies:

rule-providers:
  Reject:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/TopFreeProxies/reject.yaml
    interval: 86400

rules:
  - RULE-SET,Reject,REJECT,no-resolve
  - MATCH,节点选择